# Generated by Django 5.0 on 2024-01-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_keyword', models.CharField(max_length=255, null=True)),
                ('part_number_formal', models.CharField(max_length=255, null=True)),
                ('supplier_product_inf', models.CharField(blank=True, max_length=255, null=True)),
                ('sps_part_reversion', models.CharField(blank=True, max_length=255, null=True)),
                ('sps_ip_reversion', models.CharField(blank=True, max_length=255, null=True)),
                ('supplier_product_ip_with_fields', models.CharField(blank=True, max_length=1083, null=True)),
                ('sps_pn_supplier_edhr', models.CharField(blank=True, max_length=255, null=True)),
                ('sps_special_requirement', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
